spring.application.name=projectassignment
spring.datasource.url=jdbc:mysql://localhost:3306/projectassignment?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=2489
spring.jpa.hibernate.ddl-auto=create
server.port=9090
